### PR TITLE
Create devcontainer.json

### PR DESCRIPTION
**Pull request by XOwlPost**
Preconfigured Trunk.io devcontainer

### CODE REVIEW

**Comment by XOwlPost** [comment]
Approved review

**Comment by laurit17** [comment]
Hi, thank you for the contribution! 

We have a devcontainer config for our plugins repo, which includes the trunk feature, would you mind including that here? https://github.com/trunk-io/plugins/blob/main/.devcontainer.json

(we don't need the `npm ci` call, but having `trunk install` would be good)

**Comment by laurit17** [comment]
Hi @XOwlPost , wanted to check in on this PR. Can you add the trunk feature as discussed?

**Comment by XOwlPost** [comment]
> Hi @XOwlPost , wanted to check in on this PR. Can you add the trunk feature as discussed?

Hi laurit17, have made the requested changes pls review. Thanks.

**Comment by laurit17** [comment]
kicking the tires here one more time - I'm happy to take over this PR if needed.

**Comment by XOwlPost** [comment]
> kicking the tires here one more time - I'm happy to take over this PR if needed.

Yes, if that's a possibility would like that. Thx

**Comment by laurit17** [comment]
closing - took this over elsewhere. thank you.

**Pull request closed without merging**
