### PR TITLE
Fix stylelint packages

### PR DESCRIPTION
**Pull request by TylerJang27**
The stylelint config was referencing a package that wasn't being installed.

Also upgrades the CLI.

### CODE REVIEW

**Comment by drwpow** [comment]
In the Stylelint config, I see the following:

```
  - stylelint-config-standard-scss
  - stylelint-config-prettier
  - stylelint-config-clean-order
```

I think we need all of these packages (none are installed by default by Stylelint)?

My guess is it only erred on the first one it looked for

**Comment by drwpow** [comment]
Also, it seems that `stylelint-config-prettier` is incompatible with [Stylelint >= 15.x](https://github.com/prettier/stylelint-config-prettier/blob/master/package.json#L30), and [the package has been deprecated](https://github.com/prettier/stylelint-config-prettier). I propose we just nix it from the default config (which is separate from this PR, but also semi-related because this PR deals with packages from our default config)

**Comment by TylerJang27** [comment]
I modified the stylelint config and extra packages to be correct (fixed) and also renamed the config to the js version, which is a "lower priority" as far as stylelint is concerned, allowing us to override it more easily, and allowing the collision to be detected in the marketing repo.

**Comment by TylerJang27** [comment]
@drwpow. This is ready for re-review when you get the chance

**Review by drwpow — APPROVED** [review]
Looks great! 💯

**Comment by drwpow** [comment]
Also thanks for the ping—I missed the earlier update (sorry!)

**Pull request merged**
